export const CONSOLE_OPTIONS = [
  { consoleid: 1, name: '1292 Advanced Programmable Video System' },
  { consoleid: 2, name: '3DO Interactive Multiplayer' },
  { consoleid: 3, name: '64DD' },
  { consoleid: 4, name: 'AY-3-8606' },
  { consoleid: 5, name: 'AY-3-8760' },
  { consoleid: 6, name: 'Acorn Archimedes' },
  { consoleid: 7, name: 'Acorn Electron' },
  { consoleid: 8, name: 'Advanced Pico Beena' },
  { consoleid: 9, name: 'AirConsole' },
  { consoleid: 10, name: 'Amazon Fire TV' },
  { consoleid: 11, name: 'Amiga' },
  { consoleid: 12, name: 'Amiga CD32' },
  { consoleid: 13, name: 'Amstrad CPC' },
  { consoleid: 14, name: 'Amstrad GX4000' },
  { consoleid: 15, name: 'Amstrad PCW' },
  { consoleid: 16, name: 'Analogue electronics' },
  { consoleid: 17, name: 'Android' },
  { consoleid: 18, name: 'Apple II' },
  { consoleid: 19, name: 'Apple IIGS' },
  { consoleid: 20, name: 'Apple Pippin' },
  { consoleid: 21, name: 'Arcade' },
  { consoleid: 22, name: 'Arcadia 2001' },
  { consoleid: 23, name: 'Arduboy' },
  { consoleid: 24, name: 'Atari 2600' },
  { consoleid: 25, name: 'Atari 5200' },
  { consoleid: 26, name: 'Atari 7800' },
  { consoleid: 27, name: 'Atari 8-bit' },
  { consoleid: 28, name: 'Atari Jaguar' },
  { consoleid: 29, name: 'Atari Jaguar CD' },
  { consoleid: 30, name: 'Atari Lynx' },
  { consoleid: 31, name: 'Atari ST/STE' },
  { consoleid: 32, name: 'BBC Microcomputer System' },
  { consoleid: 33, name: 'Bally Astrocade' },
  { consoleid: 34, name: 'BlackBerry OS' },
  { consoleid: 35, name: 'Blu-ray Player' },
  { consoleid: 36, name: 'CDC Cyber 70' },
  { consoleid: 37, name: 'Call-A-Computer time-shared mainframe computer system' },
  { consoleid: 38, name: 'Casio Loopy' },
  { consoleid: 39, name: 'ColecoVision' },
  { consoleid: 40, name: 'Commodore 16' },
  { consoleid: 41, name: 'Commodore C64/128/MAX' },
  { consoleid: 42, name: 'Commodore CDTV' },
  { consoleid: 43, name: 'Commodore PET' },
  { consoleid: 44, name: 'Commodore Plus/4' },
  { consoleid: 45, name: 'Commodore VIC-20' },
  { consoleid: 46, name: 'DOS' },
  { consoleid: 47, name: 'DVD Player' },
  { consoleid: 48, name: 'Daydream' },
  { consoleid: 49, name: 'Digiblast' },
  { consoleid: 50, name: 'Donner Model 30' },
  { consoleid: 51, name: 'Dragon 32/64' },
  { consoleid: 52, name: 'Dreamcast' },
  { consoleid: 53, name: 'EDSAC' },
  { consoleid: 54, name: 'Epoch Cassette Vision' },
  { consoleid: 55, name: 'Epoch Super Cassette Vision' },
  { consoleid: 56, name: 'Evercade' },
  { consoleid: 57, name: 'FM Towns' },
  { consoleid: 58, name: 'FM-7' },
  { consoleid: 59, name: 'Fairchild Channel F' },
  { consoleid: 60, name: 'Family Computer' },
  { consoleid: 61, name: 'Family Computer Disk System' },
  { consoleid: 62, name: 'Gamate' },
  { consoleid: 63, name: 'Game & Watch' },
  { consoleid: 64, name: 'Game Boy' },
  { consoleid: 65, name: 'Game Boy Advance' },
  { consoleid: 66, name: 'Game Boy Color' },
  { consoleid: 67, name: 'Game.com' },
  { consoleid: 68, name: 'Gear VR' },
  { consoleid: 69, name: 'Gizmondo' },
  { consoleid: 70, name: 'Google Stadia' },
  { consoleid: 71, name: 'HP 2100' },
  { consoleid: 72, name: 'Handheld Electronic LCD' },
  { consoleid: 73, name: 'Hyper Neo Geo 64' },
  { consoleid: 74, name: 'HyperScan' },
  { consoleid: 75, name: 'Imlac PDS-1' },
  { consoleid: 76, name: 'Intellivision' },
  { consoleid: 77, name: 'Intellivision Amico' },
  { consoleid: 78, name: 'LaserActive' },
  { consoleid: 79, name: 'LeapTV' },
  { consoleid: 80, name: 'Leapster' },
  { consoleid: 81, name: 'Leapster Explorer/LeadPad Explorer' },
  { consoleid: 82, name: 'Legacy Computer' },
  { consoleid: 83, name: 'Legacy Mobile Device' },
  { consoleid: 84, name: 'Linux' },
  { consoleid: 85, name: 'MSX' },
  { consoleid: 86, name: 'MSX2' },
  { consoleid: 87, name: 'Mac' },
  { consoleid: 88, name: 'Mega Duck/Cougar Boy' },
  { consoleid: 89, name: 'Meta Quest 2' },
  { consoleid: 90, name: 'Meta Quest 3' },
  { consoleid: 91, name: 'Microcomputer' },
  { consoleid: 92, name: 'Microvision' },
  { consoleid: 93, name: 'N-Gage' },
  { consoleid: 94, name: 'NEC PC-6000 Series' },
  { consoleid: 95, name: 'Neo Geo AES' },
  { consoleid: 96, name: 'Neo Geo CD' },
  { consoleid: 97, name: 'Neo Geo MVS' },
  { consoleid: 98, name: 'Neo Geo Pocket' },
  { consoleid: 99, name: 'Neo Geo Pocket Color' },
  { consoleid: 100, name: 'New Nintendo 3DS' },
  { consoleid: 101, name: 'Nintendo 3DS' },
  { consoleid: 102, name: 'Nintendo 64' },
  { consoleid: 103, name: 'Nintendo DS' },
  { consoleid: 104, name: 'Nintendo DSi' },
  { consoleid: 105, name: 'Nintendo Entertainment System' },
  { consoleid: 106, name: 'Nintendo GameCube' },
  { consoleid: 107, name: 'Nintendo Switch' },
  { consoleid: 108, name: 'Nintendo Switch 2' },
  { consoleid: 109, name: 'Nuon' },
  { consoleid: 110, name: 'OOParts' },
  { consoleid: 111, name: 'Oculus Go' },
  { consoleid: 112, name: 'Oculus Quest' },
  { consoleid: 113, name: 'Oculus Rift' },
  { consoleid: 114, name: 'Oculus VR' },
  { consoleid: 115, name: 'Odyssey' },
  { consoleid: 116, name: 'Odyssey 2 / Videopac G7000' },
  { consoleid: 117, name: 'OnLive Game System' },
  { consoleid: 118, name: 'Ouya' },
  { consoleid: 119, name: 'PC (Microsoft Windows)' },
  { consoleid: 120, name: 'PC Engine SuperGrafx' },
  { consoleid: 121, name: 'PC-50X Family' },
  { consoleid: 122, name: 'PC-8800 Series' },
  { consoleid: 123, name: 'PC-9800 Series' },
  { consoleid: 124, name: 'PC-FX' },
  { consoleid: 125, name: 'PDP-1' },
  { consoleid: 126, name: 'PDP-10' },
  { consoleid: 127, name: 'PDP-11' },
  { consoleid: 128, name: 'PDP-7' },
  { consoleid: 129, name: 'PDP-8' },
  { consoleid: 130, name: 'PLATO' },
  { consoleid: 131, name: 'Palm OS' },
  { consoleid: 132, name: 'Panasonic M2' },
  { consoleid: 133, name: 'Philips CD-i' },
  { consoleid: 134, name: 'PlayStation' },
  { consoleid: 135, name: 'PlayStation 2' },
  { consoleid: 136, name: 'PlayStation 3' },
  { consoleid: 137, name: 'PlayStation 4' },
  { consoleid: 138, name: 'PlayStation 5' },
  { consoleid: 139, name: 'PlayStation Portable' },
  { consoleid: 140, name: 'PlayStation VR' },
  { consoleid: 141, name: 'PlayStation VR2' },
  { consoleid: 142, name: 'PlayStation Vita' },
  { consoleid: 143, name: 'Playdate' },
  { consoleid: 144, name: 'Playdia' },
  { consoleid: 145, name: 'Plug & Play' },
  { consoleid: 146, name: 'PocketStation' },
  { consoleid: 147, name: 'Pokémon mini' },
  { consoleid: 148, name: 'Polymega' },
  { consoleid: 149, name: 'R-Zone' },
  { consoleid: 150, name: 'SDS Sigma 7' },
  { consoleid: 151, name: 'SG-1000' },
  { consoleid: 152, name: 'Satellaview' },
  { consoleid: 153, name: 'Sega 32X' },
  { consoleid: 154, name: 'Sega CD' },
  { consoleid: 155, name: 'Sega CD 32X' },
  { consoleid: 156, name: 'Sega Game Gear' },
  { consoleid: 157, name: 'Sega Master System/Mark III' },
  { consoleid: 158, name: 'Sega Mega Drive/Genesis' },
  { consoleid: 159, name: 'Sega Pico' },
  { consoleid: 160, name: 'Sega Saturn' },
  { consoleid: 161, name: 'Sharp MZ-2200' },
  { consoleid: 162, name: 'Sharp X1' },
  { consoleid: 163, name: 'Sharp X68000' },
  { consoleid: 164, name: 'Sinclair QL' },
  { consoleid: 165, name: 'Sinclair ZX81' },
  { consoleid: 166, name: 'Sol-20' },
  { consoleid: 167, name: 'SteamVR' },
  { consoleid: 168, name: 'Super A`Can' },
  { consoleid: 169, name: 'Super Famicom' },
  { consoleid: 170, name: 'Super NES CD - ROM System' },
  { consoleid: 171, name: 'Super Nintendo Entertainment System' },
  { consoleid: 172, name: 'TRS - 80' },
  { consoleid: 173, name: 'TRS - 80 Color Computer' },
  { consoleid: 174, name: 'Tapwave Zodiac' },
  { consoleid: 175, name: 'Tatung Einstein' },
  { consoleid: 176, name: 'Terebikko / See `n Say Video Phone' },
  { consoleid: 177, name: 'Texas Instruments TI-99' },
  { consoleid: 178, name: 'Thomson MO5' },
  { consoleid: 179, name: 'Tomy Tutor / Pyuta / Grandstand Tutor' },
  { consoleid: 180, name: 'TurboGrafx-16/PC Engine' },
  { consoleid: 181, name: 'Turbografx-16/PC Engine CD' },
  { consoleid: 182, name: 'Uzebox' },
  { consoleid: 183, name: 'V.Smile' },
  { consoleid: 184, name: 'VC 4000' },
  { consoleid: 185, name: 'Vectrex' },
  { consoleid: 186, name: 'Virtual Boy' },
  { consoleid: 187, name: 'Virtual Console' },
  { consoleid: 188, name: 'Watara/QuickShot Supervision' },
  { consoleid: 189, name: 'Web browser' },
  { consoleid: 190, name: 'Wii' },
  { consoleid: 191, name: 'Wii U' },
  { consoleid: 192, name: 'Windows Mixed Reality' },
  { consoleid: 193, name: 'Windows Mobile' },
  { consoleid: 194, name: 'Windows Phone' },
  { consoleid: 195, name: 'WonderSwan' },
  { consoleid: 196, name: 'WonderSwan Color' },
  { consoleid: 197, name: 'Xbox' },
  { consoleid: 198, name: 'Xbox 360' },
  { consoleid: 199, name: 'Xbox One' },
  { consoleid: 200, name: 'Xbox Series X|S' },
  { consoleid: 201, name: 'ZX Spectrum' },
  { consoleid: 202, name: 'Zeebo' },
  { consoleid: 203, name: 'iOS' },
  { consoleid: 204, name: 'visionOS' }
];
